### ISSUE TITLE
Integrate Tekton projects with Google Analytics

### ISSUE THREAD

**Issue by GuidoBR** [renzon/tekton#41]
Web projects should have some sort of tool to know their users. Google Analytics is a natural choice to do this.

It would be easy to be done. Just include the Google Analytics javascript in the base/base.html file, and the user should insert his GA code.

I can do this if you think it's a good idea.

**Comment by renzon** [comment]
In facto I have already done that on a Tekton instance, on site www.python.pro.br. But I really don't know if every site needs it. More than that, I know some people that prefer some other open source solution because they don't like to put their data under Google Analytics. Maybe would be great documenting that if you need this kind of feature on every page, you can use tha base, once all pages inherits from it. What you thing about it?

**Comment by GuidoBR** [comment]
You do have a point. I'll write the docs for this. 

I'm studying[1] Sphynx[2] and Read the docs[3] to help creating the documentation for Tekton. What do you think?

[1] - http://www.jeffknupp.com/blog/2013/08/16/open-sourcing-a-python-project-the-right-way/
[2] - http://sphinx-doc.org/
[3] - https://readthedocs.org/
