### ISSUE TITLE
manager.py should print the created files, not their contents

### ISSUE THREAD

**Issue by GuidoBR** [renzon/tekton#55]
It's more useful to see what files were created instead of their contents.

I volunteer to do that change if you agree.

**Comment by renzon** [comment]
This is true. The code content was useful on beginning so I could see the code generation without going to files. In fact manager.py is little mess right now. I have used no framework for CLI on that time. But since I talked with some people and discoreved that there are some interesting options: http://docs.python-guide.org/en/latest/scenarios/cli/. You can make only your change. But if you wanna dig deeper, once I know you like sometimes, fell free to play around ;)

**Comment by GuidoBR** [comment]
Done it.

I have other issues to create about manager.py, will do a refactor using one of those frameworks later. :)
